# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweeted_by',
            field=models.ManyToManyField(related_name='retweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
